; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=bpfel -mcpu=v3 -filetype=asm < %s | FileCheck %s
;
; A monotonic (relaxed) atomicrmw whose result is unused may be selected to
; the non-fetching instructions (lock *(uXX *)(addr) op= val), but when the
; result is live it must be selected to the fetch variants: the lock form
; does not return the old value. sub is lowered as a fetch_add/lock += of
; the negated value.
;
; Source (32-bit shown; the 64-bit variants use long):
;   void test_fetch_<op>_32_noret(int _Atomic *i) {
;     (void)__c11_atomic_fetch_<op>(i, 1, memory_order_relaxed);
;   }
;   int test_fetch_<op>_32_ret(int _Atomic *i) {
;     return __c11_atomic_fetch_<op>(i, 1, memory_order_relaxed);
;   }

define void @test_fetch_add_32_noret(ptr %i) {
; CHECK-LABEL: test_fetch_add_32_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w2 = 1
; CHECK-NEXT:    lock *(u32 *)(r1 + 0) += w2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw add ptr %i, i32 1 monotonic, align 4
  ret void
}

define i32 @test_fetch_add_32_ret(ptr %i) {
; CHECK-LABEL: test_fetch_add_32_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w0 = 1
; CHECK-NEXT:    w0 = atomic_fetch_add((u32 *)(r1 + 0), w0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw add ptr %i, i32 1 monotonic, align 4
  ret i32 %0
}

define void @test_fetch_add_64_noret(ptr %i) {
; CHECK-LABEL: test_fetch_add_64_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r2 = 1
; CHECK-NEXT:    lock *(u64 *)(r1 + 0) += r2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw add ptr %i, i64 1 monotonic, align 8
  ret void
}

define i64 @test_fetch_add_64_ret(ptr %i) {
; CHECK-LABEL: test_fetch_add_64_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 1
; CHECK-NEXT:    r0 = atomic_fetch_add((u64 *)(r1 + 0), r0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw add ptr %i, i64 1 monotonic, align 8
  ret i64 %0
}

define void @test_fetch_sub_32_noret(ptr %i) {
; CHECK-LABEL: test_fetch_sub_32_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w2 = 1
; CHECK-NEXT:    w2 = -w2
; CHECK-NEXT:    lock *(u32 *)(r1 + 0) += w2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw sub ptr %i, i32 1 monotonic, align 4
  ret void
}

define i32 @test_fetch_sub_32_ret(ptr %i) {
; CHECK-LABEL: test_fetch_sub_32_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w0 = 1
; CHECK-NEXT:    w0 = -w0
; CHECK-NEXT:    w0 = atomic_fetch_add((u32 *)(r1 + 0), w0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw sub ptr %i, i32 1 monotonic, align 4
  ret i32 %0
}

define void @test_fetch_sub_64_noret(ptr %i) {
; CHECK-LABEL: test_fetch_sub_64_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r2 = 1
; CHECK-NEXT:    r2 = -r2
; CHECK-NEXT:    lock *(u64 *)(r1 + 0) += r2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw sub ptr %i, i64 1 monotonic, align 8
  ret void
}

define i64 @test_fetch_sub_64_ret(ptr %i) {
; CHECK-LABEL: test_fetch_sub_64_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 1
; CHECK-NEXT:    r0 = -r0
; CHECK-NEXT:    r0 = atomic_fetch_add((u64 *)(r1 + 0), r0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw sub ptr %i, i64 1 monotonic, align 8
  ret i64 %0
}

define void @test_fetch_and_32_noret(ptr %i) {
; CHECK-LABEL: test_fetch_and_32_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w2 = 1
; CHECK-NEXT:    lock *(u32 *)(r1 + 0) &= w2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw and ptr %i, i32 1 monotonic, align 4
  ret void
}

define i32 @test_fetch_and_32_ret(ptr %i) {
; CHECK-LABEL: test_fetch_and_32_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w0 = 1
; CHECK-NEXT:    w0 = atomic_fetch_and((u32 *)(r1 + 0), w0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw and ptr %i, i32 1 monotonic, align 4
  ret i32 %0
}

define void @test_fetch_and_64_noret(ptr %i) {
; CHECK-LABEL: test_fetch_and_64_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r2 = 1
; CHECK-NEXT:    lock *(u64 *)(r1 + 0) &= r2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw and ptr %i, i64 1 monotonic, align 8
  ret void
}

define i64 @test_fetch_and_64_ret(ptr %i) {
; CHECK-LABEL: test_fetch_and_64_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 1
; CHECK-NEXT:    r0 = atomic_fetch_and((u64 *)(r1 + 0), r0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw and ptr %i, i64 1 monotonic, align 8
  ret i64 %0
}

define void @test_fetch_or_32_noret(ptr %i) {
; CHECK-LABEL: test_fetch_or_32_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w2 = 1
; CHECK-NEXT:    lock *(u32 *)(r1 + 0) |= w2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw or ptr %i, i32 1 monotonic, align 4
  ret void
}

define i32 @test_fetch_or_32_ret(ptr %i) {
; CHECK-LABEL: test_fetch_or_32_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w0 = 1
; CHECK-NEXT:    w0 = atomic_fetch_or((u32 *)(r1 + 0), w0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw or ptr %i, i32 1 monotonic, align 4
  ret i32 %0
}

define void @test_fetch_or_64_noret(ptr %i) {
; CHECK-LABEL: test_fetch_or_64_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r2 = 1
; CHECK-NEXT:    lock *(u64 *)(r1 + 0) |= r2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw or ptr %i, i64 1 monotonic, align 8
  ret void
}

define i64 @test_fetch_or_64_ret(ptr %i) {
; CHECK-LABEL: test_fetch_or_64_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 1
; CHECK-NEXT:    r0 = atomic_fetch_or((u64 *)(r1 + 0), r0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw or ptr %i, i64 1 monotonic, align 8
  ret i64 %0
}

define void @test_fetch_xor_32_noret(ptr %i) {
; CHECK-LABEL: test_fetch_xor_32_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w2 = 1
; CHECK-NEXT:    lock *(u32 *)(r1 + 0) ^= w2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw xor ptr %i, i32 1 monotonic, align 4
  ret void
}

define i32 @test_fetch_xor_32_ret(ptr %i) {
; CHECK-LABEL: test_fetch_xor_32_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    w0 = 1
; CHECK-NEXT:    w0 = atomic_fetch_xor((u32 *)(r1 + 0), w0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw xor ptr %i, i32 1 monotonic, align 4
  ret i32 %0
}

define void @test_fetch_xor_64_noret(ptr %i) {
; CHECK-LABEL: test_fetch_xor_64_noret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r2 = 1
; CHECK-NEXT:    lock *(u64 *)(r1 + 0) ^= r2
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw xor ptr %i, i64 1 monotonic, align 8
  ret void
}

define i64 @test_fetch_xor_64_ret(ptr %i) {
; CHECK-LABEL: test_fetch_xor_64_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    r0 = 1
; CHECK-NEXT:    r0 = atomic_fetch_xor((u64 *)(r1 + 0), r0)
; CHECK-NEXT:    exit
entry:
  %0 = atomicrmw xor ptr %i, i64 1 monotonic, align 8
  ret i64 %0
}
